Creating step for secrets in test script

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -22,21 +22,47 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-
+      
+      - name: Set password and username secrets as environment variables
+        run: |
+        
+          if [ -z "${{ secrets.MTC_PASSWD }}" ]; then 
+            echo "Secret MTC_PASSWD is missing!" 
+            exit 1 
+          fi 
+          if [ -z "${{ secrets.MTC_USERNAME }}" ]; then 
+            echo "Secret MTC_USERNAME is missing!" 
+            exit 1 
+          fi 
+          if [ -z "${{ secrets.ODS_USERNAME}}" ]; then 
+            echo "Secret ODS_USERNAME is missing!" 
+            exit 1 
+          fi 
+          if [ -z "${{ secrets.ODS_PASSWD }}" ]; then 
+            echo "Secret ODS_PASSWD is missing!" 
+            exit 1 
+          fi 
+          
+          echo "MTC_PASSWD=${{ secrets.MTC_PASSWD }}" >> $GITHUB_ENV 
+          echo "MTC_USERNAME=${{ secrets.MTC_USERNAME }}" >> $GITHUB_ENV 
+          echo "ODS_USERNAME=${{ secrets.ODS_USERNAME }}" >> $GITHUB_ENV 
+          echo "ODS_PASSWD=${{ secrets.ODS_PASSWD }}" >> $GITHUB_ENV 
       - name: Run tests
         run: |
           if [ -f docker-compose.test.yml ]; then
             docker-compose --file docker-compose.test.yml build
             docker-compose --file docker-compose.test.yml run sut
           else
+          
             docker build \
+            --no-cache \
             --secret id=MTC_PASSWD,env=MTC_PASSWD \
-            --secret id=MTC_USRNAME,env=MTC_USRNAME \
-            --secret id=MTC_ODS_USRNAME,env=MTC_ODS_USRNAME \
+            --secret id=MTC_USERNAME,env=MTC_USERNAME \
+            --secret id=ODS_USERNAME,env=ODS_USERNAME \
             --secret id=ODS_PASSWD,env=ODS_PASSWD \
-            --build-arg MTC_USRNAME="${MTC_USRNAME}" \
+            --build-arg MTC_USERNAME="${MTC_USERNAME}" \
             --build-arg MTC_PASSWD="${MTC_PASSWD}" \
-            --build-arg MTC_ODS_USRNAME="${MTC_ODS_USRNAME}" \
+            --build-arg ODS_USERNAME="${ODS_USERNAME}" \
             --build-arg ODS_PASSWD="${ODS_PASSWD}" . --file Dockerfile
           fi
-
+          
